### ISSUE TITLE
Automated detection of JavaFX Application Thread

### ISSUE THREAD

**Issue by stephansann** [Dansoftowner/jSystemThemeDetector#12]
Hi @Dansoftowner

If found an interesting function within the GestureFX code:

```
	private static void runLaterOrNowIfOnFXThread(Runnable r) {
		if (Platform.isFxApplicationThread()) r.run();
		else Platform.runLater(r);
	}
```
(see https://github.com/tom91136/GestureFX/blob/master/gesturefx/src/main/java/net/kurobako/gesturefx/GesturePane.java)

I think this could be interesting for jSystemThemeDetector, right!? At least if the library is running within an JavaFX context.

If you would add this to the calling code of the OsThemeDetector Listeners, users wouldn't have to worry about it and you could remove the warning from the README. Or am I missing something here?

Let me know your thoughts.

Best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann ,

Yes, I already knew about this. 
The reason why I didn't implement is that I don't want this library to be JavaFX-dependent.

Anyways, thanks for your suggestion!

Best regards
Daniel
