### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by ahmedriad01** [Dansoftowner/jSystemThemeDetector#24]
### I get these error messages:

**SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.**

All that I do with this library
```
val detector = OsThemeDetector.getDetector()
val isDarkThemeUsed = detector.isDark
JOptionPane.showMessageDialog(null, if (isDarkThemeUsed) "You are using dark theme" else "You are using light theme")
```

**Comment by Dansoftowner** [comment]
Look at #11.
