### ISSUE TITLE
v3.0 - modularity

### ISSUE THREAD

**Issue by stephansann** [Dansoftowner/jSystemThemeDetector#6]
Hi!
I added v3.0 to my project.
To make it work I had to "brute force" it by adding "--add-opens com.jthemedetector/com.jthemedetector=com.sun.jna" to my Maven argLine.

Would be nice if I wouldn't have to do this 😉
(Adding an "opens" to the module-info.java" on your side should fix it IMHO.)

Thanks again
Stephan

**Comment by Dansoftowner** [comment]
Should be fixed in version `3.1` :)

**Comment by stephansann** [comment]
Looking good so far 👍🏻
Thanks for the quick fix 🙏🏻
