### ISSUE TITLE
com.jthemedetecor.OsThemeDetector#isDark does not seem to work under macOS Big Sur 11.3

### ISSUE THREAD

**Issue by stephansann** [Dansoftowner/jSystemThemeDetector#9]
Hi @Dansoftowner 

After updating to macOS Big Sur 11.3 the ThemeDetector does not seem to work any more.

com.jthemedetecor.OsThemeDetector#isDark delivers ```false```, even though the appearance it set to dark.

Also the change listener does not seem to trigger any more.

Could you please check?

Thanks and best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann ,

Thanks for reporting this issue!
I would ask you to tell me what is the value of this expression : `OsThemeDetector.getDetector().getClass().getName()`.

Best regards
Daniel

**Comment by stephansann** [comment]
Sure - that would be:

```com.jthemedetecor.OsThemeDetector$EmptyDetector```

HTH, Stephan

**Comment by Dansoftowner** [comment]
Hi!

Thanks again for reporting this serious issue!
Hopefully updating to version `3.5` solves the problem.

If not, tell me!

Best regards
Daniel

**Comment by stephansann** [comment]
Hi again
Sorry, not fixed yet. But at least I found out why the system is not identified as macOS:

<img width="1077" alt="Screen Shot 2021-04-29 at 09 25 29" src="https://user-images.githubusercontent.com/9678681/116515885-2eb04c80-a8cd-11eb-9615-a847239a281c.png">

HTH & best regards
Stephan

**Comment by stephansann** [comment]
Maybe you could also be interested in this:

<img width="1077" alt="Screen Shot 2021-04-29 at 09 31 44" src="https://user-images.githubusercontent.com/9678681/116516348-cdd54400-a8cd-11eb-807b-4cfb61d74fd6.png">

**Comment by Dansoftowner** [comment]
Okay, check out version `3.6`.

**Comment by Dansoftowner** [comment]
I think It will finally solve the problem

**Comment by stephansann** [comment]
Yes, looks good again now 😊

Thanks for the quick repair 👍🏻
